.TH XPP 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
xpp \- The X/Windows User Interface for ProofPower
.SH SYNOPSIS
.B xpp
[Standard X Toolkit options] [-blocking] [-readonly] [-havefonts] [-filename file] [-command command-line]
.SH DESCRIPTION
The program 
.I "xpp"
provides a convenient way to prepare, check and execute
ProofPower scripts under the X Windows System.
.I "xpp"
combines a general purpose text editor with a command interface for
operating the {\Product} specification and proof facilities.
Consult the 
.I "xpp"
.I "User Guide"
for full information.
Once 
.I "xpp"
is running, you can also use its help menu to find further information
on how to use it.
.LP
In the command line syntax above,  `
.I "Standard X toolkit options"
', refers to the options which are automatically supported by X Toolkit applications.
An example is the option `
.I "-display"
', which may be used to specify the X server on which you wish 
.I "xpp"
output to be displayed.
Consult the UNIX manual page on X(7) for more information on these options.
.LP
.I "-blocking"
is used to specify that
.I "xpp"
should not return control to the calling process until the user exits the user interface.
Without this option,
.I "xpp"
runs in the background.
.LP
.I "-readonly"
is used to specify that
.I "xpp"
should turn on the read-only flag for the file to be edited.
Without this option,
.I "xpp"
will determine the value of the read-only flag from the access mode of the file and
will warn you if the file is read-only.
.LP
.LP
.I "-havefonts"
is used to suppress the attempt that
.I "xpp"
would otherwise make to add the ProofPower font directory to the font path
if the ProofPower fonts are not already available.
.I "-filename file"
is used to specify a file to be loaded in to the editor when 
.I "xpp"
starts.
.LP
.I "-command command-line"
is used to specify the UNIX command line to be run.
Typically, this is one of the commands that invoke {\Product}.
See the description of the commands, 
.IR "pp" ,
.I "hol"
and 
.I "zed"
for more information.
If you omit this option then 
.I "xpp"
runs without the command interface.
.LP
If either of
.I "file"
or
.I "command-line"
is specified as an empty string,
.I "xpp"
will start up displaying a dialogue box inviting you to enter the missing information interactively.
.LP
You can abbreviate the options to 
.IR "xpp" .
For example: 
.LP
xpp -disp myserver:0 -file myscript.doc -comm pp -d mydatabase
.LP
.SH SEE ALSO
.I "pp(1)",
.I "hol(1)",
.I "zed(1)"

.I "USR031: ProofPower - Xpp User Guide"
