.TH XPP 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
xpp \- The X/Windows User Interface for ProofPower
.SH SYNOPSIS
.B xpp
[Standard X Toolkit options] [xpp option | command option] ...
.SH DESCRIPTION
The program 
.I "xpp"
provides a convenient way to prepare, check and execute
ProofPower scripts under the X Windows System.
.I "xpp"
combines a general purpose text editor with a command interface for
operating the {\Product} specification and proof facilities.
Consult the 
.I "xpp"
.I "User Guide"
for full information.
Once 
.I "xpp"
is running, you can also use its help menu to find further information
on how to use it.
.LP
In the command line syntax above,
.I "Standard X toolkit options"
refers to the options which are automatically supported by X Toolkit applications.
An example is the option
.I "-display"
which may be used to specify the X server on which you wish 
.I "xpp"
output to be displayed.
Consult the UNIX manual page on X(7) for more information on these options.
.LP
An
.I "xpp option"
is one of:
.TP
.B "-b"
"blocking" - run in the foreground not in the background.
.TP
.B "-c command [arg ...]"
"command line" - run
.B "command"
with the specified arguments.
.TP
.B "[-f] name"
"file name" - open file
.B "name"
for editing.
.TP
.B "-h"
"have fonts" - do not attempt to load any fonts.
.TP
.B "-r"
"read-only" - start with the read-only option turned on.
.LP
In the form with
.B "-c command"
everything after
.B "command"
is taken as comprising the argument list
.B "[arg ...]"
for the command.
.B "-f"
may be omitted if
.B "name"
is not itself an
xpp or command option.
.LP
The command options are recognised using an option description
string configured into xpp.
It is configured by
default to recognise the command options for the program
.B "pp"
that is used to run an interactive ProofPower session.
.LP
If there are no command options and 
.B "-c command"
has
not been specified, then xpp will run an editor-only session. If there are command
options, but no
.B "-c command,"
then xpp will run a command session
using a default command to run - this will be the
script
.B "pp"
in typical use of xpp. The command will
be passed the concatenation of all the command options as its arguments.
If
.B "-c command"
is specified, xpp will run a command session
with the command line exactly as specified after
.B "-c."
It is an
error for a command option to appear before
.B "-c."

.SH SEE ALSO
.I "pp(1)"
.I "hol(1)"
.I "zed(1)"

.I "USR031: ProofPower - Xpp User Guide"
