.TH PP 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
pp \- run an interactive or batch ProofPower session
.SH SYNOPSIS
.B pp
-d database[#theoryname] [-i file] ... [-f file] ... [-n|-s] [-v|-q]] [-- ml_flags]
.br
.B hol
[-d database[#theoryname]] [-i file] ... [-f file] ...[-n|-s] [-v|-q]] [-- ml_flags]
.br
.B zed
[-d database[#theoryname]] [-i file] ... [-f file] ... [-n|-s] [-v|-q]] [-- ml_flags]
.SH DESCRIPTION
.I "pp"
runs ProofPower on the indicated database. If no
.I "-d database"
is provided to
.IR "pp" ,
the function fails.
.LP
.I "hol"
and
.I "zed"
are identical to
.I "pp"
except that they use default databases
.B "hol"
and
.B "zed"
respectively, and hence
.I "-d database"
is optional.
.LP
For portability, the database name should be given without any architecture- or
compiler-specific prefixes or suffixes.
Any such prefixes or suffixes will be added automatically by
.IR "pp" ,
If the resulting file name is an absolute path name (i.e., starts with a `/' character),
then that is used as the database file name.
If the resulting file name is not an absolute path name,
.I "pp"
searches for the database file using the
search path given in the environment variable
.IR "\$PPDATABASEPATH",
if set.
If
.IR "\$PPDATABASEPATH"
is not set,
.I "pp"
searches for the database in the current directory, then in the subdirectory
.IR "db"
of the user's home directory and then in the subdirectory
.IR  "db"
of the ProofPower installation directory.
.LP
If specified,
.I "theoryname"
gives the name of a theory to be made the
current theory at the start of the session.
If
.I "theoryname"
is not specified, then
current theory will be set to the theory current when the database was last saved by
.B "save_and_quit"
or, if just created,
to the cache theory for the database.
The files identified by any
.I "[-i file]"
options are then
executed in turn.
If
.I "-f file"
options are provided, then the files specified are loaded in batch mode. Once loading is complete the database is saved and the batch session is terminated. The saving of the database can be suppress by providing the
.I "-n"
flag. The default action if any of the files fails to load is for the session to terminate at that point and the database is not saved. By providing the
.I "-s"
flag, the user can indicate to the system to save the database in batch mode upon failure. The
.I "-n"
and
.I "-s"
flags are mutually exclusive. If they are both provided, a warning message is issued and the
.I "-s"
flag is ignored.
.LP
By default, the production of subgoal package output in a batch load is as determined by the value of the flag
.I "subgoal_package_quiet"
stored in the database.
If the
.I "-v"
flag is specified to
.I "pp"
, the subgoal package output is produced whereas if the
.I "-q"
flag is specified, it is suppressed.
.LP
If
.I "-f files"
is not provided, then the system then issues a prompt for user input.
.LP
Flags which appear after
.I "-- "
are passed directly onto the Standard ML system for processing. This mechanism can be used to tailor the heap size under SML/NJ: e.g.,
.IR "pp -d hol -- -h 32000" .
.SH DIAGNOSTICS
The environment variable
.I "PPCOMPILER"
may be used to select between the Poly/ML
or SML/NJ compiler if {\Product} has been installed for both compilers.
If it is set, the value of this variable must be either ``
.I "POLYML"
'' or ``
.I "SMLNJ"
''.
.LP
The environment variable
.IR "PPLINELENGTH" ,
if set, determines the initial value of the
string control
.IR "line_length" .
This gives the line length used by various listing
facilities, e.g.,
.I "print_theory"
and
.IR "output_theory" .
In interactive use,
the
.I "xpp"
interface will set
.I "PPLINELENGTH"
automatically if it has not been
set explicitly by the user.
.I "pp"
prints a message and exits (with status~1) if
the database cannot be accessed or if the theory name specified
as part of the
.I "-d"
argument
does
not exist in the database.
.SH SEE ALSO
.IR "pp_make_database(1)" ,

.IR "pp_list(1)" ,

.I "pp_read(1)"
.LP
.I "USR029: ProofPower - HOL Reference Manual"
.LP
.I "USR030: ProofPower - Z Reference Manual"
