.TH PP_LIST 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
pp_list \- list information from a ProofPower database
.SH SYNOPSIS
.B pp_list
[-c] -d database[#theory] [-i scripts] [-l lang] [-v] theory ...
.br
.B pp_list
-d database[#theory] [-i scripts] [-l lang1 [-l lang2 ...]] [-v]
.br
.B pp_list
[-c] -d database [-i scripts] [-l lang1 [-l lang2 ...]] [-v] -a
.SH DESCRIPTION
.I "pp_list"
is used to obtain selected information from
a ProofPower database.
.LP
In the first form of use, where a list 
of one or more theory names is specified,
.I "pp_list"
uses ProofPower to generate on its standard output
listings of the indicated theories held in the
database given by the 
.I "-d"
option in a form suitable
for processing by 
.IR "doctex" .
.LP
If there is no 
.I "-l"
option then the theory lister used
will depend on the language of the theory.
If the language is ``HOL'' then 
.B "output_theory"
is used.
Otherwise it will attempt to use a function named:
<language in lower case>_output_theory
and only if that doesn't exist will it use 
.BR "output_theory" .
All but the first language will be ignored.
.LP
If the 
.I "-l\ lang"
option is given then it will take the language code of all theories given to be 
.IR "lang" ,
and then work as above.
.LP
If no 
.I "-d"
option is given then the function fails.
.LP
Any cache theory (i.e. the theory name is in the list
returned by 
.BR "get_cache_theories" )
will be printed
with most of the theory detail elided, unless the 
.I "-c"
option is given.
.LP
In the second form, with no list of theory names, 
.I "pp_list"
lists the names of all the theories in the database one
per line on its standard output channel in a sorted order.
If any 
.I "-l"
options are given then only theories
whose language is one of those listed will be noted.
.LP
The third form, with 
.IR "-a" ,
is like the first but causes all
of the theories in the database to be listed in a sorted order.
If any 
.I "-l"
options are given then only theories
whose language is one of those given will be listed,
and they will be individually printed according to their own language.
.LP
In any of the three forms,
the program will start a session as if by command
.I "pp"
with the supplied 
.I "-d"
and 
.I "-i"
arguments (if any),
and it is in this environment that the theory
listing is done.
The output of this startup will be suppressed, including any indication of failure to load the initialisation scripts.
.LP
Each theory is, if possible, made current, or at least in scope, when it is listed.
.LP
In any form 
.I "-v"
indicates the log of the preprocessing
should also be output.
.SH DIAGNOSTICS
.I "pp_list"
prints a message and exits (with the value 1)
if the database or any of the theories does not exist.
The log of the failure is sent to the standard output, the message to the
error output.
.SH SEE ALSO
.IR "zed_list" ,

.IR "hol_list" ,

.IR "pp" ,

.I "pp_make_database"
.LP
.I "USR029: ProofPower - HOL Reference Manual"
.LP
.I "USR030: ProofPower - Z Reference Manual"
