=IGN
********************************************************************************
wrk051.pp: this file is part of the PPHol system

Copyright (c) 2002 Lemma 1 Ltd.

See the file LICENSE for your rights to use and change this file.

Contact: Rob Arthan < rda@lemma-one.com >
********************************************************************************
% wrk051.pp  ℤ $Date: 2002/10/17 16:20:01 $ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $

=IGNORE
To use the makefile generated by this document starting from
scratch see the ``Interface'' subsection (use forward search
in textedit upon ``Interface'').
=TEX
\documentclass[a4paper,12pt]{article}
\usepackage{A4}
\usepackage{Lemma1}
\usepackage{ProofPower}
\usepackage{latexsym}
\usepackage{epsf}
\def\Title{Creating Example ProofPower Databases}
\def\Reference{DS/FMU/IED/WRK051}
\def\Version{\VCVersion}
\def\Date{\FormatDate{\VCDate}}
% \TPPtype{Literate Script}
% \TPPkeywords{HOL}
\def\Authors{K.~Blackburn }
% \TPPauthorisation{R.D.~Arthan & FST Team Leader}
\def\Abstract{\centering{\bf Abstract}\par This document contains the makefile, plus its associated files,
	that produces example databases for \Product.
	The ``Interface'' section describes the creation and
	use of this makefile from a user's point of view.}
\def\Distribution{\parbox[t]{4.0in}{%
	Library
}}

%\ftlinepenalty=9999
\makeindex
% \underscoreoff
\begin{document}
\FrontPage

\vfill
\begin{center}
\bf Copyright \copyright\ : Lemma 1 Ltd. \number\year
\end{center}


\section{DOCUMENT CONTROL}

\subsection{Contents List}
\tableofcontents
% \listoftables

\subsection{Document Cross References}

\bibliographystyle{fmu}
\bibliography{fmu}

\subsection{Changes History}

\begin{description}
\item[Issues 1.1 (1993/03/03)-1.3 (1993/03/11) (To 10th March 1993)]
Initial versions.
\item[Issue 1.4 (1993/09/22) (22nd September 1993)]
Addition of new HOL tutorial, changed to work with new release mechanism.
\item[Issue 1.5 (1993/09/23) (23rd September 1993)]
Reordering of dependencies for all\_hol, addition of spc001.th, spc002.th
\item[Issue 1.6 (1993/09/28) (28th September 1993)]
Change from usr011x.sml, usr013x.sml to usr011x.doc, usr013x.doc
\item[Issue 1.9 (1994/09/06) (25th August 1994)]
Changed \$INSTALLDIR to be \$PPPPINSTALLDIR.

\item[Issue 1.15 (2002/10/17)] Copyright and banner updates for open source release.
\item[Issue 1.16 (2002/10/17)] PPHol-specific updates for open source release
\item[Issue 1.17 (2008/02/11)] The demo scripts can now be run as tests by the hol and zed make files.
\item[2014/07/23]
Augmented old RCS version numbers in the changes history with dates.
Dates will be used in place of version numbers in future.
\item[2015/04/15]
Now uses new date and version macros from doctex
%%%% END OF CHANGES HISTORY %%%%
\end{description}

\subsection{Changes Forecast} \label{ChangesForecast}
None.

\newpage
\section{GENERAL}
\subsection{Scope}

This document provides documentation, a makefile and auxiliary scripts
for the process of producing certain example databases
for a \Product{} user.

\subsection{Introduction}

This document contains the literate script of a makefile ($wrk051.mkf$) and
a number of auxiliary files which are scripts for other programs.  This
material allows the creation of example databases containing \Product{}
tutorial and case study material.  The user's interface to this material
is given in section
\ref{INTERFACE}.

To produce
the makefile the program {\tt sieve} is used to process this document,
with the {\tt sml} option.  The  result is the creation of a makefile,
together with a number of small utility-files that are inputs for
\Product{}.  Most the makefile entries are concerned with the creation
or updating of various example databases.

The commentary upon the makefile assumes some knowledge of the UNIX
{\tt make} command.  The key item of knowledge is the form and meaning
of a standard makefile entry.
=GFT Example makefile entry
target1 target2 : dependency1 dependency2 dependency3
	command1
	command2
	command3
	command4
=TEX
To use such an entry in a makefile the user might type:
=GFT csh
make -f makefile target1
=TEX
If so, {\tt make} will first recursively use the rest of the makefile to
do what processing is necessary for each of the $dependency_i$ (this may
be nothing).  It will then determine whether $target1$ exists and has a
``time of last change'' after the ``time of last change'' of each
$dependency_i$.  If so {\tt make} will halt.  If not, then it will execute
each of the $command_i$ in sequence, in different shells, and then halt.

It is the above {\tt make} algorithm, in combination with a single file (a
database) containing all the effect of cumulative loads in \Product{}, that leads to the system of ``flags'' in the makefile entries in section
\ref{FIRSTFLAG} and beyond.

See UNIX documentation\cite{sunOS4.1manuals} for further details, such as
a description of macros and pattern matching rules.

\newpage
\subsection{Interface}
\label{INTERFACE}
In the following descriptions the text marked by:
=GFT csh
marked text
=TEX
may be cut and pasted without change from the source file of this document
(wrk051.pp) into a SunView shell tool or command tool.

To produce the example databases, start in a directory with the necessary
files of:
=GFT
(1)     usr004.pp
(2)     usr011A.pp usr011B.pp usr011C.pp usr011D.pp
(3)     usr011E.pp usr011T.pp usr011S.pp usr011X.pp
(4)     usr013A.pp usr013B.pp usr013C.pp usr013D.pp usr013E.pp
(5)     usr013F.pp usr013G.pp usr013H.pp usr013S.pp usr013X.pp
(6)     usr022_slides.pp usr023_slides.pp
(7)     wrk022.pp wrk043.pp wrk044.pp wrk046.pp
(8)     wrk051.pp (this file)
=TEX
These should all be present in the subdirectory $docs$ of the \Product{}
installation directory.  However, it is better to work with copies of
these files,  in a new directory, e.g. $examples$.  If using a \Product{}
installation made in the manner suggested in \cite{DS/FMU/IED/USR007} then
copies may be made by:
=GFT csh
cd $PPINSTALLDIR
mkdir examples
cd $PPINSTALLDIR/docs
cp usr004.pp  usr011A.pp usr011B.pp usr011C.pp usr011D.pp \
      usr011E.pp usr011T.pp usr011S.pp usr011X.pp \
      usr013A.pp usr013B.pp usr013C.pp usr013D.pp usr013E.pp \
      usr013F.pp usr013G.pp usr013H.pp usr013S.pp usr013X.pp \
      usr022_slides.pp usr023_slides.pp wrk022.pp wrk043.pp \
      wrk044.pp wrk046.pp wrk051.pp $PPINSTALLDIR/examples
=TEX
Then create the makefile {\tt wrk051.mkf} by :
=GFT csh
cd $PPINSTALLDIR/examples
sieve sml < wrk051.pp
=TEX
Having produced the makefile ( {\tt wrk051.mkf}) and utilities, as above,
there are then several options for further commands.

To print this document (assuming {\tt pstex} without arguments sends
output to the desired printer):
=GFT csh
make -f wrk051.mkf wrk051.prt
=TEX

To create a child \Product{} database containing the effect of loading the  tutorial scripts of usr004 \cite{DS/FMU/IED/USR004}:
=GFT csh
make -f wrk051.mkf usr004.tutorial
=TEX
The resulting database can be invoked by:
=GFT
hol -d example_hol
=TEX

Similarly for usr011\cite{DS/FMU/IED/USR011}, creating a database suitable
for loading the \ProductZ{} exercises and trying solutions for them,
by hand:
=GFT csh
make -f wrk051.mkf usr011.tutorial
=TEX
The resulting database can be invoked by:
=GFT
zed -d example_zed
=TEX

Similarly for usr013\cite{DS/FMU/IED/USR013}, creating a database suitable
for loading the \ProductHOL{} exercises and trying solutions for them, by
hand:
=GFT csh
make -f wrk051.mkf usr013.tutorial
=TEX
The resulting database can be invoked by:
=GFT
zed -d example_hol
=TEX

Similar entries also exist for $usr022$\cite{DS/FMU/IED/USR022} and
$usr023$\cite{DS/FMU/IED/USR023}, rather than $usr004$.
=GFT csh
make -f wrk051.mkf usr022.tutorial
make -f wrk051.mkf usr023.tutorial
=TEX

To create a database containing the effect of
loading the exercise scripts for usr011 (which will also run the tutorial
scripts for $usr011$, if not already done):
=GFT csh
make -f wrk051.mkf usr011.zexercises
=TEX

To create a database containing the effect of
loading the solutions scripts for usr011 (which will also run the
exercises, if not already done):
=GFT csh
make -f wrk051.mkf usr011.zsolutions
=TEX

To create a database containing the effect of
loading the exercise scripts for usr013 (which will also run the tutorial
scripts for $usr013$, if not already done):
=GFT csh
make -f wrk051.mkf usr011.exercises
=TEX

To create a database containing the effect of loading the solutions scripts for usr011 (which will also run the exercises, if not already done):
=GFT csh
make -f wrk051.mkf usr011.solutions
=TEX

To tidy up afterwards, deleting all created databases and files, execute:
=GFT csh
make -f wrk051.mkf clean_examples
=TEX

To remove all auxiliary files created by ``sieving'' this one:
=GFT csh
rm -f wrk051.mkf \
	wrk051_delete_theories_usr004.sml \
	wrk051_delete_theories_usr011.sml \
	wrk051_delete_theories_zexercises.sml \
	wrk051_delete_theories_usr013.sml \
	wrk051_delete_theories_exercises.sml \
	wrk051_delete_theories_spc001.sml \
	wrk051_delete_theories_spc002.sml \
	wrk051_delete_theories_usr022.sml \
	wrk051_delete_theories_usr023.sml \
	wrk051_delete_theories_wrk022.sml \
	wrk051_delete_theories_wrk043.sml \
	wrk051_delete_theories_wrk044.sml \
	wrk051_delete_theories_wrk046.sml \
	wrk051_delete_theories_wrk050.sml
=TEX

The file {\tt pp\_install}, to be found in the installation directory,
copies all the files needed into a new directory and runs all the
\Product{} scripts to generate the two databases ($`arch`example\_zed.db$)
and ($`arch`example\_hol.db$).  It copies these two databases into the
$`arch`bin$ directory, and cleans up afterwards.  This file needs to be
run from the release directory.

It is advised that the {\tt changeParent} command is run on the new databases,
the new parents being {\tt sun4pp\_hol.db} and {\tt sun4pp\_zed}, found
in the subdirectory {\tt sun4bin}.  The script {\tt pp\_install} does this.

\section{START OF MAKEFILE}

=DUMP wrk051.mkf
# wrk051.mkf
#	A makefile that produces example databases.
#	Created from:  $Header: /home/rda/zed/RCS/wrk051.pp,v 1.16 2002/10/17 16:20:01 rda Exp rda $

=TEX

\section{PRELIMINARIES}

\subsection{Macros}

The first two macros below define the base names of the example databases.
=DUMPMORE wrk051.mkf
EHOLDB = example_hol
EZEDDB = example_zed

=TEX

=TEX

The following are the comments returned at the end of a successful or
failed  make:
=DUMPMORE wrk051.mkf
SUCCESS_MESSAGE = "make command succeeded"
FAILURE_MESSAGE = "make command failed"

=TEX

\subsection{Default}
The default action of the makefile is to print a message.
The default is indicated by it being the first target in the
makefile.
=DUMPMORE wrk051.mkf
default :
	@echo Use:
	@echo "         make -f wrk051.mkf all"
	@echo to create example ProofPower databases for HOL and Z.
	@echo See document DS/FMU/IED/WRK051 for further details.

=TEX

\subsection{File Group Definitions}

Groups of files which are processed in similar ways are defined as make variables in the following.

Note that, pro-tem. the HOL tutorial is run using ext and the zed using unicode, and this determines different processing of the various files by the makefile.

=DUMPMORE wrk051.mkf

SPCPPS=	   ⦏spc001.pp⦎ ⦏spc002.pp⦎ ⦏spc003.pp⦎ ⦏spc004.pp⦎ ⦏spc005.pp⦎
USR011PPS= ⦏usr011A.pp⦎ ⦏usr011B.pp⦎ ⦏usr011C.pp⦎ ⦏usr011D.pp⦎ ⦏usr011E.pp⦎ ⦏usr011T.pp⦎ \
	   ⦏usr011S.pp⦎ ⦏usr011X.pp⦎ ⦏usr023_slides.pp⦎ ⦏wrk050.pp⦎ ⦏wrk051.pp⦎
USR013PPS= ⦏usr013A.pp⦎ ⦏usr013B.pp⦎ ⦏usr013C.pp⦎ ⦏usr013D.pp⦎ ⦏usr013E.pp⦎ ⦏usr013F.pp⦎ \
	   ⦏usr013G.pp⦎ ⦏usr013H.pp⦎ ⦏usr013X.pp⦎ ⦏usr013S.pp⦎
OTHERUSRPPS= ⦏usr004.pp⦎ ⦏usr022_slides.pp⦎
USRPPS=	   $(USR011PPS) $(USR013PPS) $(OTHERUSRPPS)
WRKPPS=  ⦏wrk022.pp⦎ ⦏wrk043.pp⦎ ⦏wrk044.pp⦎ ⦏wrk046.pp⦎
X11PPS= $(SPCPPS) $(USR013PPS) $(OTHERUSRPPS) $(WRKPPS)
ALLPPS= $(SPCPPS) $(USRPPS) $(WRKPPS)

USRPPSMLS=  $(SPCPPS:.pp=.ppsml) $(USR013PPS:.pp=.ppsml) $(OTHERUSRPPS:.pp=.ppsml) $(WRKPPS:.pp=.ppsml)
USRXSMLS=   $(USR011PPS:.pp=.sml)

USR011SMLS= $(USR011PPS:.pp=.sml)
USR013SMLS= $(USR013PPS:.pp=.sml)
USRSMLS=    $(USR011SMLS) $(USR013SMLS)
WRKSMLS=    $(WRKPPS:.pp=.sml)
X11PPSMLS=  $(X11PPS:.pp=.ppsml)
X11SMLS=    $(X11PPS:.pp=.sml)
ALLSMLS=$(ALLPPS:.pp=.sml)

=TEX
\subsection{Pattern Matching Rules} \label{PatternMatchingRules}
See {\tt make} documentation for how the following work.  They provide
the ``standard'' processing rules for:
\begin{description}
\item[.pp -]
documents,
\item[.sml -]
Standard ML files, usually derived from documents,
\item[.tex -]
\LaTeX{} files derived from documents,
\item[.dvi -]
files displayable by {\tt dvipage} or printable by {\tt pstex},
\item[.prt -]
dummy files, used to invoke printing.
\end{description}
=DUMPMORE wrk051.mkf
.SUFFIXES: .pp .sml .tex .dvi .prt
%.tex: %.pp
	pptex $*

%.dvi: %.tex
	texdvi $*
	- bibtex $*
	texdvi $*
	texdvi $*

$(X11PPSMLS): %.ppsml: %.pp
	ppsml -f holutf8.svf $*
	mv $*.sml $*.ppsml

$(X11SMLS): %.sml: %.ppsml
	pp_file_conv -u <$*.ppsml >$*.sml

$(USR011SMLS): %.sml: %.pp
	ppsml -f holutf8.svf $*

%.prt: %.dvi
	pstex $*

=TEX

The following .pp files are supplied in a release of \Product.
=DUMPMORE wrk051.mkf
$(USRPPS):
	@echo Missing $@, which should have been present in release
	exit 1

=TEX

\section{PREPARING CLEAN DATABASES}
\label{FIRSTFLAG}
The two flags, $wrk051\_hol.flag$ and $wrk051\_zed.flag$ are two empty
files, whose ``time of last change'' is the time of creation of the
example databases.  Various items later in this makefile have these flags
amongst their dependencies.  This means that, amongst other reasons for
reloading, such items are reloaded if their previous load was made prior
to the creation of the appropriate example database.  If the dependencies
of these items were the database filenames themselves, then a reload would
be needed on any change to the databases, such as another, orthogonal,
load.  However, the databases themselves will still be recreated if the
flags are used as dependencies when they are out of step with their parents
(or are not there at all!).
=DUMPMORE wrk051.mkf
HOLPARENT=$(shell echo $${PPHOLPARENT:-hol})
⦏wrk051_hol.flag⦎ $(EHOLDB) :
	pp_make_database -f -p $(HOLPARENT) $(EHOLDB)
	touch wrk051_hol.flag

ZEDPARENT=$(shell echo $${PPZEDPARENT:-zed})
⦏wrk051_zed.flag⦎ $(EZEDDB) :
	pp_make_database -f -p $(ZEDPARENT) $(EZEDDB)
	touch wrk051_zed.flag
=TEX
\section{MAKING THE TUTORIAL MANUAL (usr004)}
The following pattern of file creation and makefile entry is used in most
of the following sections, though we only comment upon it in this one.

The following command creates a file:
=INLINEFT
wrk051_delete_theories_usr004.sml
=TEX
{} that is used to delete, if present, the theories that would be created
by loading $usr004.sml$.  If the theories were present the load of
$usr004.sml$ would fail.  A similar file is created for each of the items
that may be added into the example databases.
=VDUMP wrk051_delete_theories_usr004.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "Peanissimo" handle Fail _ => ());
(force_delete_theory "ordinals" handle Fail _ => ());
=TEX

The following creates, if necessary, an example HOL database (via
=INLINEFT
wrk051_hol.flag
=TEX
{}).
It then creates an $.sml$ file from $usr004.pp$, loads the above
theory-deleting file into the example database, and then loads this formal
text of $usr004.pp$.  It then saves the database with the results of the
above loads.  Finally, it touches a flag, $usr004.tutorial$, so that the
``time of last change'' for the flag is the time of last loading
$usr004.sml$.
=DUMPMORE wrk051.mkf
⦏usr004.tutorial⦎: wrk051_hol.flag usr004.pp usr004.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_usr004  -f usr004
	touch usr004.tutorial

=TEX

\section{MAKING THE Z TUTORIAL MANUAL (usr011)}

\subsection{Z Tutorial Source Files}

\begin{center}
\begin{tabular}{|l|l|} \hline
usr011.* & top level document \\\hline
usr011A.* &  Ch. 2 - Z Language\\\hline
usr011B.* &  Ch. 3 - Z Predicate Calculus\\\hline
usr011C.* &  Ch. 4 - Z Expressions\\\hline
usr011D.* &  Ch. 5 - Z Paragraphs\\\hline
usr011E.* &  Ch. 6 - An Example Specification and Proof\\\hline
usr011T.* &  Ch. 7 - The Z ToolKit\\\hline
usr011X.* &  Exercises\\\hline
usr011S.* &  Solutions\\\hline
\end{tabular}
\end{center}

\subsection{Z Tutorial Make Entries}

=VDUMP wrk051_delete_theories_usr011.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "usr011" handle Fail _ => ());
=TEX

=VDUMP wrk051_delete_theories_zexercises.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "z_exercises_1" handle Fail _ => ());
(force_delete_theory "z_exercises_2" handle Fail _ => ());
(force_delete_theory "z_exercises_3" handle Fail _ => ());
(force_delete_theory "z_exercises_4" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏usr011.tutorial⦎: wrk051_zed.flag usr011A.sml usr011B.sml \
		usr011C.sml usr011D.sml usr011E.sml usr011T.sml \
		usr023_slides.sml
	zed -d $(EZEDDB) -f wrk051_delete_theories_usr011.sml -f usr011A.sml \
		-f usr011B.sml -f usr011C.sml -f usr011D.sml \
		-f usr011T.sml -f usr011E.sml -f usr023_slides.sml
	touch usr011.tutorial
	
⦏usr011.zexercises⦎: usr011.tutorial usr011X.pp usr011X.sml
	zed -d $(EZEDDB) -f wrk051_delete_theories_zexercises.sml -f usr011X.sml
	touch usr011.zexercises
	
⦏usr011.zsolutions⦎: usr011.zexercises usr011S.pp usr011S.sml
	zed -d $(EZEDDB) -f usr011S.sml
	touch usr011.zsolutions

=TEX

\section{MAKING THE HOL TUTORIAL MANUAL (usr013)}

\subsection{HOL Tutorial Source Files}

\begin{center}
\begin{tabular}{|l|l|} \hline
usr013.* & top level document \\\hline
usr013A.* &  Ch. 2 - Introduction\\\hline
usr013B.* &  Ch. 3 - HOL type system\\\hline
usr013C.* &  Ch. 4 - HOL terms\\\hline
usr013D.* &  Ch. 5 - Theories\\\hline
usr013E.* &  Ch. 6 - Forward proof\\\hline
usr013F.* &  Ch. 7 - Goal Oriented proof\\\hline
usr013G.* &  Ch. 8 - Predicate calculus\\\hline
usr013H.* &  Ch. 9 - Induction\\\hline
usr013X.* &  Exercises\\\hline
usr013S.* &  Solutions\\\hline
\end{tabular}
\end{center}

\subsection{HOL Tutorial Make Entries}

=VDUMP wrk051_delete_theories_usr013.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "usr013" handle Fail _ => ());
=TEX

=VDUMP wrk051_delete_theories_exercises.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "usr013X" handle Fail _ => ());
=TEX

=VDUMP wrk051_delete_theories_solutions.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "Shankar-Rushby-International" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏usr013.tutorial⦎: wrk051_hol.flag usr013A.sml usr013B.sml \
		usr013C.sml usr013D.sml usr013E.sml \
		usr013F.sml usr013G.sml usr013H.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_usr013.sml \
		-f usr013A.sml -f usr013B.sml -f usr013C.sml \
		-f usr013D.sml -f usr013E.sml -f usr013F.sml \
		-f usr013G.sml -f usr013H.sml
	touch usr013.tutorial
	
⦏usr013.exercises⦎: usr013.tutorial usr013X.pp usr013S.pp usr013X.sml usr013S.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_exercises.sml -f usr013X.sml
	touch usr013.exercises
	
⦏usr013.solutions⦎: usr013.exercises usr013S.pp usr013X.sml usr013S.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_solutions.sml -f usr013S.sml
	discgarb $(EHOLDB)
	touch usr013.solutions

=TEX

\section{MAKING TUTORIAL OVERHEADS (usr022)}

=VDUMP wrk051_delete_theories_usr022.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "tutorial" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏usr022.tutorial⦎: wrk051_hol.flag usr022_slides.pp usr022_slides.sml
	hol -d $(EHOLDB)  -f wrk051_delete_theories_usr022.sml  -f usr022_slides
	touch usr022.tutorial

=TEX

\section{MAKING Z TUTORIAL OVERHEADS (usr023)}

=VDUMP wrk051_delete_theories_usr023.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "usr023" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏usr023.tutorial⦎: wrk051_zed.flag usr023_slides.pp usr023_slides.sml
	zed -d $(EZEDDB) -f wrk051_delete_theories_usr023.sml -f usr023_slides
	touch usr023.tutorial

=TEX

\section{MAKING HOL FORMALISED (spc001)}

=VDUMP wrk051_delete_theories_spc001.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "spc001" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏spc001.th⦎: wrk051_hol.flag spc001.pp spc001.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_spc001.sml -f spc001.sml
	touch spc001.th

=TEX

\section{MAKING HOL SEMANTICS (spc002)}

=VDUMP wrk051_delete_theories_spc002.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "spc002" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏spc002.th⦎: wrk051_hol.flag spc002.pp spc002.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_spc002.sml -f spc002.sml
	touch spc002.th

=TEX

\section{MAKING MODAL LOGIC (wrk022)}

=VDUMP wrk051_delete_theories_wrk022.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "wrk022" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏wrk022.th⦎: wrk051_hol.flag wrk022.pp wrk022.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_wrk022.sml  -f wrk022.sml
	touch wrk022.th

=TEX

\section{MAKING RAMSEYS THEOREM (wrk043)}

=VDUMP wrk051_delete_theories_wrk043.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "ramsey" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏wrk043.th⦎: wrk051_hol.flag wrk043.pp wrk043.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_wrk043.sml -f wrk043.sml
	touch wrk043.th

=TEX

\section{MAKING FINITENESS THEOREMS (wrk044)}

=VDUMP wrk051_delete_theories_wrk044.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "fin_thms" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏wrk044.th⦎: wrk051_hol.flag wrk044.pp wrk044.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_wrk044.sml -f wrk044.sml
	touch wrk044.th

=TEX

\section{MAKING FINITENESS THEOREMS (wrk046)}

=VDUMP wrk051_delete_theories_wrk046.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "lib_thms" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏wrk046.th⦎: wrk051_hol.flag wrk046.pp wrk046.sml
	hol -d $(EHOLDB) -f wrk051_delete_theories_wrk046.sml -f wrk046.sml
	touch wrk046.th

=TEX

\section{MAKING CASE STUDY (wrk050)}

=VDUMP wrk051_delete_theories_wrk050.sml
(* created from wrk051.pp ℤ $Revision: 1.16 $ $RCSfile: wrk051.pp,v $ $Date: 2002/10/17 16:20:01 $ *)
(force_delete_theory "wrk050" handle Fail _ => ());
=TEX

=DUMPMORE wrk051.mkf
⦏wrk050.th⦎: wrk051_zed.flag wrk050.pp wrk050.sml
	zed -d $(EZEDDB) -f wrk051_delete_theories_wrk050.sml -f wrk050.sml
	touch wrk050.th

=TEX

$wrk050.dvi$ is created by the standard rule for $.dvi$ files.
		
\section{CREATE ALL DATABASES}
The following create and populates the example HOL and Z databases.
=DUMPMORE wrk051.mkf
⦏all_hol⦎: spc001.th spc002.th usr004.tutorial usr013.exercises \
	wrk022.th wrk044.th wrk043.th wrk046.th
	@echo All module tests passed.

⦏all_zed⦎: usr011.zexercises wrk050.th
	@echo All module tests passed.

⦏all⦎ : all_hol all_zed

=TEX

$all$ can be ``undone'' by $clean\_examples$.

\section{TIDYING UP THE FILE STORE}
Clean out all example database material that might be created during
an execution of this makefile:
=DUMPMORE wrk051.mkf
⦏clean_examples⦎ :
	rm -f $(EHOLDB) $(EZEDDB)
	rm -f wrk051_hol.flag wrk051_zed.flag
	rm -f usr004.tutorial usr022.tutorial usr023.tutorial
	rm -f usr011.tutorial usr011.zexercises usr011.zsolutions
	rm -f usr013.tutorial usr013.exercises usr013.solutions
	rm -f spc001.th spc002.th spc001.sml spc002.sml spc001.ppsml spc002.ppsml
	rm -f wrk022.th wrk043.th wrk044.th wrk046.th wrk050.th
	rm -f usr022_slides.sml usr023_slides.sml usr004.sml
	rm -f $(ALLSMLS) $(USRPPSMLS)
	rm -f wrk050.sml

=TEX

To remove all auxiliary files created by ``sieving'' {\tt wrk051.pp}
(we refrain from having a makefile entry delete its own makefile!):
=GFT csh
rm -f wrk051.mkf wrk051_*.*
=TEX
\section{make ENDINGS}
The following text causes {\tt make} to output the appropriate message
upon finished processing with either a successful or
failed ``make''.
=DUMPMORE wrk051.mkf
⦏.FAILED⦎ :
	@ echo "*** $(FAILURE_MESSAGE) ***" 1>&2
	exit 1

⦏.DONE⦎ :
	@ echo "*** $(SUCCESS_MESSAGE) ***" 1>&2

=TEX

\newpage

\twocolumn[\section{INDEX}] \label{Index}

\footnotesize
\printindex

\onecolumn

\end{document}

