name: ProofPower CI (Container)

on:
  push:
    branches: [ master, utf8 ]
  pull_request:
    branches: [ master, utf8 ]
  workflow_dispatch:

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y locales polyml texlive texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra libmotif-dev xfig groff xfonts-utils x11-xserver-utils git gawk
          locale-gen en_US.ISO8859-1
          update-locale LANG=en_US.ISO8859-1
          locale-gen en_US.UTF-8
          update-locale
          locale -a
      - name: Build all packages
        run: |
          export PPDIR=`pwd`
          cd src && make all
      - name: Run tests
        run: cd src && make testreport
