name: ProofPower CI Fedora

on:
  push:
    branches: [ master, utf8 ]
  pull_request:
    branches: [ master, utf8 ]
  workflow_dispatch:

jobs:
  build-test-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y polyml polyml-doc texlive texlive-epsf motif motif-devel groff mkfontdir xfig git gawk xmodmap redhat-rpm-config
      - name: Build all packages
        run: |
          export PPDIR=`pwd`
          cd src && make all
      - name: Run tests
        run: cd src && make testreport