name: ProofPower CI

on:
  workflow_dispatch:

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y polyml texlive texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra libmotif-dev xfig groff xfonts-utils x11-xserver-utils git gawk
          sudo apt-get install -y locales
          sudo locale-gen en_US.ISO8859-1
          sudo update-locale LANG=en_US.ISO8859-1
          sudo locale-gen en_US.UTF-8
          sudo update-locale
          locale -a
      - name: Build all packages
        run: |
          export PPDIR=`pwd`
          cd src && make all
      - name: Run tests
        run: cd src && make testreport
        
