name: ProofPower CI

on:
  push:
    branches: [ master, utf8 ]
  pull_request:
    branches: [ master, utf8 ]
  workflow_dispatch:

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y polyml texlive texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra xfig groff xfonts-utils git gawk
      - name: Source dev_env
        run: . ./dev_env
      - name: Build all packages
        run: cd src && make all
      - name: Run tests
        run: cd src && make testreport
        
