.TH conv_ascii 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
conv_ascii \-  convert between the ASCII and extended character set formats for a ProofPower document
.SH SYNOPSIS
.B conv_ascii
[-r] [-K] [-k keyword_file_name] <filename> ...
.br
.B conv_extended
[-r] [-K] [-k keyword_file_name] <filename> ...
.SH DESCRIPTION
.B "conv_ascii"
converts ProofPower documents using the extended
character set into ASCII keyword format. 
.B "conv_extended"
performs
the opposite conversion.
.LP
The 
.B "filename"
arguments may be just the
base-name, perhaps with a directory name prefix, or may include the 
.I ".doc"
suffix. By default,
the result of the conversion is checked by
converting in the opposite direction and comparing with the input.
If the check is successful, the 
.I ".doc"
file is then replaced by the result of the conversion.
If the conversion appears to be unsuccessful the output of the conversion
is placed in a file with suffix 
.I ".asc"
or 
.I ".ext"
in the current directory, and the 
.I ".doc"
file is
left unchanged. 
.LP
If 
.B "-r"
is specified no check is made and the output of the conversion is placed
in a file with suffix 
.I ".asc"
or 
.IR ".ext" .
.LP
Note that the check will always fail on a file containing a mixture of extended
characters and ASCII keywords. Use 
.B "-r"
and then, if all is well, overwrite
the 
.I ".doc"
file with the 
.I ".asc"
or 
.I ".ext"
file using 
.B "mv(1)"
or 
.B "cp(1)"
to convert a such file into a homogeneous one.
.LP
The check will also fail if the file is already in the desired format,
in which case there is no need to run the conversion program.
.LP
The 
.B "-K"
and 
.B "-k"
options indicate the
keyword files to be used as for 
.B "doctex"
and 
.B "docsml"
(and are only
needed if fonts other than those supplied with ProofPower are being used.)
.LP
.SH SEE ALSO
.I "docpr"
.LP
.I "USR001: ProofPower - Document Preparation"
.LP
