.TH docdvi 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
docdvi \-  produce a .dvi file from a ProofPower document
.SH SYNOPSIS
.B docdvi
[-v] [-f view_file_name] [-K] [-k keyword_file_name]
.br
	[-e edit_file_name] [-p TeX_program_name] [-%calN%] <filename> ...
.SH DESCRIPTION
Shell script that combines the actions of 
.IR "doctex" ,

.I "bibtex"
(which is part of the basic \TeX{} distribution) and 
.I "texdvi"
with
the intention of fully processing a simple document from its 
.I ".doc"
form to a printable 
.I ".dvi"
file. 
.LP
The option $-\cal N$ controls how
many times LaTeX should be invoked, the default is three (i.e.,
`
.B "-3"
'), the values of $\cal N$ may be in the range one to four
inclusive.
The other options are as for 
.I "doctex"
and 
.IR "texdvi" .
.LP
LaTeX and 
.I "bibtex"
are run so that if they detect
errors and prompt for input they will read an end of file and thus stop
immediately.
.LP
In some cases an extra run of LaTeX may be required.  In these cases
LaTeX will output the message: `{\em LaTeX Warning: Label(s) may
have changed. Rerun to get cross-references right.}'
.SH SEE ALSO
.IR "doctex" ,
.I "texdvi"
.LP
.I "USR001: ProofPower - Document Preparation"
