.TH docpr 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
docpr \- print out files containing ProofPower symbols verbatim
.SH SYNOPSIS
.B docpr
[-n] [-p] [-s] [-v] [-w width] <filename> ...
.SH DESCRIPTION
Shell script that prints out files that may contain extended characters
in a verbatim-like manner.  Lines may be numbered in the output by
using the
.B "-n"
option.  Lines are folded at at~80 characters wide, or
at the width given by the
.B "-w\;\;width"
option.  The output may be
viewed on screen with the
.B "-s"
option, the default is to print the
output.  By default all intermediate files are deleted, with the
.B "-p"
option the
.I ".dvi"
file will be preserved.  With the
.B "-v"
option
details of the files processed are listed on the standard output.
.SH SEE ALSO
.IR "doctex(1)" ,
.I "texdvi(1)"
.LP
.I "USR001: ProofPower - Document Preparation"
