.TH doctex 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
doctex \- extract TeX or Standard ML view of a ProofPower document
.SH SYNOPSIS
.B doctex
[-v] [-f view_file_name] [-e edit_script]
.br
		[-K] [-k keyword_file_name] <filename> ...
.br
.B docsml
[-v] [-f view_file_name] [-K] [-k keyword_file_name] <filename> ...
.SH DESCRIPTION
Shell scripts that sieve each of their 
.B "filename"
arguments to produce
various output files.  These arguments may be given just as the
base-name, perhaps with a directory name prefix, or may include the 
.I ".doc"
suffix.  When the 
.B "-v"
option is
set details of the files read and written are shown on the standard
output.  The default steering files are named 
.I "sieveview"
and {\tt
sievekeyword} and looked for first in the current directory, second on
the callers execution path (from the UNIX environment variable
.IR "\$PATH" ).
The default viewfile may be changed with the 
.B "-f"
option.
The default keyword file may be suppressed with the 
.B "-K"
option.
Additional keyword files may be given with the 
.B "-k"
option which may be used
several times.
The 
.B "-e"
option identifies the name of a script of 
.I "ex"
commands which are used to edit the 
.I ".tex"
file.
.LP
The output file from 
.I "doctex"
has suffix 
.I ".tex"
and is intended for processing with 
.IR "texdvi" .
The output file from 
.I "docsml"
has suffix 
.I ".sml"
and is typically processed by loading
it into a {\Product} database.
.SH SEE ALSO
.IR "texdvi" ,
.I "docdvi"
.LP
.I "USR001: ProofPower - Document Preparation"
.LP
