.TH pptexenv 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
pptexenv \- Run a command in environment to pick up ProofPower TeX files
.SH SYNOPSIS
.B pptexenv
[-v] command [options]
.SH DESCRIPTION
This shell scripts runs a command, typically a TeX DVIWARE command such as
.B "dvips"
, with the environment variables used by TeX commands set to pick up TeX files from the ProofPower installation in addition to their current settings, if any.
.LP
The 
.B "-v"
option causes the script to print out the enviroment variables before running the command.
.SH SEE ALSO
.IR "texdvi(1)" ,
.I "docdvi(1)"
.LP
.I "USR001: ProofPower - Document Preparation"
.LP
