.TH texdvi 1 "17 Apr 2003" "Lemma One" "Unix Programmer's Manual"
.SH NAME
texdvi \-  generate a .dvi file and a .sid file from a .tex file
.SH SYNOPSIS
.B texdvi
[-v] [-b] [-p TeX_program_name] <filename> ...
.SH DESCRIPTION
Shell script that runs LaTeX on each of the 
.B "filename"
arguments
to produce the corresponding 
.I ".dvi"
file.  These arguments may be
just the base-name, perhaps with a directory name prefix, or may include the 
.I ".tex"
suffix.  When the 
.B "-v"
option is set details of the 
.I ".tex"
and
.I ".dvi"
files read and
written are shown on the standard output.  To support indexing this
script ensures that a 
.I ".sid"
file exists before LaTeX is called;
when LaTeX completes any 
.I ".idx"
file is sorted to create
a
.I ".sid"
file ready for the next time 
.I "texdvi"
is used.  When
initially producing a 
.I ".dvi"
file 
.I "texdvi"
will need to be run
up to four times so that the derived information such as tables of
contents and inter-page references stabilise.
.LP
The LaTeX program is 
.I "latex"
by default but a different program
may be specified with the 
.B "-p"
option.
.LP
If the
.B "-b"
option is set, the BibTeX program is run after running LaTeX.
.SH SEE ALSO
.IR "texdvi(1)" ,
.I "docdvi(1)"
.LP
.I "USR001: ProofPower - Document Preparation"
.LP
